# Generated by Django 4.0.2 on 2022-03-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('num_user', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер пользователя')),
                ('user_id', models.CharField(max_length=100, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('online_status', models.CharField(max_length=30, verbose_name='Когда заходил')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('town', models.CharField(max_length=100, verbose_name='Город')),
                ('languages', models.CharField(max_length=100, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группы')),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_key', to='server.infouser', verbose_name='Номер пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посты')),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_key', to='server.infouser', verbose_name='Номер пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Геолокации')),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geolocation_key', to='server.infouser', verbose_name='Номер пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.CharField(blank=True, max_length=100, null=True, verbose_name='Друзья')),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friends_key', to='server.infouser', verbose_name='Номер пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарии')),
                ('num_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments_key', to='server.infouser', verbose_name='Номер пользователя')),
            ],
        ),
    ]
