# Generated by Django 4.0.4 on 2022-05-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': 'Друга', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='geolocation',
            options={'verbose_name': 'Геолокацию', 'verbose_name_plural': 'Геолокации'},
        ),
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Информацию о пользователе', 'verbose_name_plural': 'Информация о пользователе'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
    ]
