# Generated by Django 4.0.2 on 2022-06-05 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_comments_num_user_alter_friends_num_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timecomment',
            field=models.TimeField(blank=True, default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='posts',
            name='timepost',
            field=models.TimeField(blank=True, default=datetime.time(16, 0)),
        ),
    ]
