# Generated by Django 4.0.2 on 2022-06-05 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_comments_timecomment_posts_timepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='weekday_comment',
            field=models.CharField(blank=True, max_length=2, verbose_name='День недели коммента'),
        ),
        migrations.AddField(
            model_name='posts',
            name='weekday_post',
            field=models.CharField(blank=True, max_length=2, verbose_name='День недели поста'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timecomment',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), verbose_name='Время коммента'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timepost',
            field=models.TimeField(blank=True, default=datetime.time(16, 0), verbose_name='Время поста'),
        ),
    ]
