# Generated by Django 4.0.2 on 2022-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_comments_weekday_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='weekday_comment',
            field=models.IntegerField(blank=True, verbose_name='День недели коммента'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='weekday_post',
            field=models.IntegerField(blank=True, verbose_name='День недели поста'),
        ),
    ]
